<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.bemuisoft.quantum</groupId>
    <artifactId>quantum-pom</artifactId>
    <version>1.0.0</version>
  </parent>

  <artifactId>quantum-simulators</artifactId>
  <version>1.0.0</version>
  <name>Quantum Simulators</name>
  <description>Yet another quantum computer simulator, lightweight.</description>

  <dependencies>
	<dependency>
		<groupId>org.bemuisoft.quantum</groupId>
		<artifactId>quantum-api</artifactId>
		<version>1.2.0</version>
	</dependency>
	<dependency>
		<groupId>org.bemuisoft.quantum</groupId>
		<artifactId>quantum-test-api</artifactId>
		<version>1.2.0</version>
		<scope>test</scope>
	</dependency>
  </dependencies>

</project>